worker_processes auto;
events { worker_connections 1024; }

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile      on;
    keepalive_timeout 65;

    lua_package_path "/usr/share/nginx/lua/?.lua;;";

    server {
        listen 80;
        root /usr/share/nginx/html;
        index index.html;

        # 上传体积上限
        client_max_body_size 20m;
        client_body_buffer_size 8m;

        location = /login.html {}
        location = /setup.html {}

        location = /api/logout {
            content_by_lua_block {
                ngx.header["Set-Cookie"] = "token=; Path=/; HttpOnly; Max-Age=0";
                return ngx.redirect("/login.html");
            }
        }

        location /api/ {
            content_by_lua_file /usr/share/nginx/lua/api.lua;
        }

        location / {
            access_by_lua_file /usr/share/nginx/lua/auth.lua;
            try_files $uri $uri/ =404;
			add_header Cache-Control "no-store, no-cache, must-revalidate" always;
			add_header Pragma "no-cache" always;
			add_header Expires "0" always;
        }
    }
}
