worker_processes auto;
events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;

    lua_package_path "/usr/share/nginx/lua/?.lua;;";
    lua_shared_dict user_cache 10m;

    server {
        listen 80;
        root /usr/share/nginx/html;
        index index.html;

        # 配置目录
        set $config_path "/usr/share/nginx/config";

        # 接口路由
        location /api/auth {
            content_by_lua_file /usr/share/nginx/lua/auth.lua;
        }
        location /api/setup {
            content_by_lua_file /usr/share/nginx/lua/init-user.lua;
        }
        location /api/upload {
            content_by_lua_file /usr/share/nginx/lua/upload.lua;
        }
        location /api/logout {
            content_by_lua_block {
                ngx.header["Set-Cookie"] = "token=; Path=/; Max-Age=0"
                return ngx.redirect("/login.html")
            }
        }

        # 静态页面鉴权控制
        location ~ ^/(index.html|js/|css/|photos/|thumb/) {
            access_by_lua_file /usr/share/nginx/lua/auth.lua;
        }

        # 登录页、初始化页面免鉴权
        location ~ ^/(login.html|setup.html) {
            try_files $uri $uri/;
        }
    }
}
